### ISSUE TITLE
On main, three tests are failing as of July 29, 2024

### ISSUE THREAD

**Issue by georgematheos** [probcomp/b3d#89]
@nishadgothoskar if you have a moment can you please take a quick look at these?

```
tests/test_image_posterior_resolution_invariance.py
tests/test_mug_handle_posterior.py
tests/test_mug_smc_pose_inference_synthetic_and_real.py
```

**Comment by eightysteele** [comment]
👋🏻 hey @nishadgothoskar and @georgematheos

I'm putting together a reproducible environment for `b3d`. To spot check that it's _reasonably_ correct, I'm keeping track of testing parity against `main`.

I just created a fresh `gcp` instance and installed the latest `b3d` environment (`main` at commit `507481f`). I was able to reproduce the failures that @georgematheos reported along with two others:

- tests/test_feature_track_data.py
- tests/test_likelihood_invariances.py

In case it's helpful, here's a summary below (along with a full log [here](https://gist.github.com/eightysteele/6cdb2c3b4352c7645766fd0538e88446))! 

```bash
(b3d) ~/b3d$ git log main -1
commit 507481fe9770ac1eb8dbeb7d509f7d9b992b21d1 (HEAD -> main, origin/main, origin/HEAD)
Author: georgematheos <georgematheos@gmail.com>
Date:   Mon Jul 29 17:30:09 2024 -0400
    In `tests/sama4d`, flip the convention from `[y, x]` to `[x, y]` (#88)

(b3d) ~/b3d$ export XLA_PYTHON_CLIENT_PREALLOCATE="false"
(b3d) ~/b3d$ export XLA_PYTHON_CLIENT_ALLOCATOR="platform"

(b3d) ~/b3d$ ./run_tests.sh 

=============================================================== short test summary info ================================================================
FAILED tests/test_feature_track_data.py::test_unity_data - EOFError: No data left in file
FAILED tests/test_image_posterior_resolution_invariance.py::TestImgResolutionInvariance::test_peaky - TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
FAILED tests/test_image_posterior_resolution_invariance.py::TestImgResolutionInvariance::test_uncertain - TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
FAILED tests/test_likelihood_invariances.py::test_resolution_invariance - TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
FAILED tests/test_likelihood_invariances.py::test_distance_to_camera_invarance - TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
FAILED tests/test_mug_handle_posterior.py::TestMugHandlePosterior::test_gridding_posterior - TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
FAILED tests/test_mug_smc_pose_inference_synthetic_and_real.py::test_renderer_full - ValueError: vmap in_axes must be an int, None, or a tuple of entries corresponding to the positional arguments passed to the function, but got len(...
================================================ 7 failed, 25 passed, 111 warnings in 344.25s (0:05:44) ================================================
```

**Comment by georgematheos** [comment]
Hi @eightysteele, thank you for sharing this!

Interestingly, these are mostly different errors than what I am seeing -- I neither get the EOFError, nor the TypeError, from these messages.  For me, the test summary is

```bash
=============================================== short test summary info ================================================
FAILED tests/test_image_posterior_resolution_invariance.py::TestImgResolutionInvariance::test_peaky - ValueError: vmap in_axes must be an int, None, or a tuple of entries corresponding to the positional arguments pass...
FAILED tests/test_image_posterior_resolution_invariance.py::TestImgResolutionInvariance::test_uncertain - ValueError: vmap in_axes must be an int, None, or a tuple of entries corresponding to the positional arguments pass...
FAILED tests/test_mug_handle_posterior.py::TestMugHandlePosterior::test_gridding_posterior - ValueError: vmap in_axes must be an int, None, or a tuple of entries corresponding to the positional arguments pass...
FAILED tests/test_mug_smc_pose_inference_synthetic_and_real.py::test_renderer_full - ValueError: vmap in_axes must be an int, None, or a tuple of entries corresponding to the positional arguments pass...
================================ 4 failed, 28 passed, 112 warnings in 331.58s (0:05:31) ================================
```
I am also at commit
```bash
commit 507481fe9770ac1eb8dbeb7d509f7d9b992b21d1 (HEAD -> main, origin/main, origin/HEAD)
Author: georgematheos <georgematheos@gmail.com>
Date:   Mon Jul 29 17:30:09 2024 -0400

    In `tests/sama4d`, flip the convention from `[y, x]` to `[x, y]` (#88)
```

**Comment by eightysteele** [comment]
@georgematheos Thanks! Just to check my understanding, did you happen run it from a freshly created instance or from an existing one? If the latter, there are probably some differences between the two environments (which is the thing I'm trying to isolate).

The errors I shared above were reproduced on a newly created instance with this command:

```bash
gcloud compute instances create $INSTANCE_NAME \
  --zone=$ZONE \
  --image-family="common-cu123-ubuntu-2204-py310" \
  --image-project=deeplearning-platform-release \
  --maintenance-policy=TERMINATE \
  --boot-disk-size=400GB \
  --machine-type g2-standard-32 \
  --accelerator="type=nvidia-l4,count=1" \
  --metadata="install-nvidia-driver=True"
```

Then I logged in and ran `install.sh` followed by `run_tests.sh` (without making any other changes to the environment).

If at some point you do spin up a new instance and run tests on main, I'd be super interested if you're able to reproduce the errors I'm seeing. Totally not urgent though, this isn't blocking me.

**Comment by georgematheos** [comment]
@eightysteele yes -- the log I shared is the result of running the tests on an existing instance.  I have run `./install.sh` recently on the existing instance, but from within an existing conda environment, so it is possible that my Python environment is also different from what would be created if I did a fresh install.

And yes, sounds good!  I am not sure I will have time for much coding today or tomorrow, but on Thursday I can try spinning up a new instance and running the tests there.  If it is helpful, I can also try to debug these errors then.

**Comment by nishadgothoskar** [comment]
Hi, just catching up on this thread. I know the source of the test failures and will fix them as soon as I'm at my desk

**Comment by eightysteele** [comment]
@georgematheos zero pressure! I'll keep this fresh environment around for a baseline. If @nishadgothoskar merges fixes, I'll run it again and we'll see where we're at. All to say, no action needed—I'll keep you posted!

**Comment by sritchie** [comment]
Boom, happy to close this out!
